-- 50 Millionaire: 180 new easy-tier seed questions
-- IMPORTANT:
-- 1) Run 01_migrate_difficulty.sql before this file.
-- 2) These rows are imported inactive and NEEDS_HUMAN_REVIEW.
-- 3) Do not activate until answer/hint/ambiguity review is complete.
-- 4) Existing medium/hard bank is NOT deleted or modified by this seed.

BEGIN;

INSERT INTO public.questions (
  external_id, question_text,
  option_a, option_b, option_c, option_d,
  correct_option, hint_text,
  level, color, category, difficulty,
  expected_solve_seconds,
  verification_status, active, source_type, source_reference
)
VALUES
('MME180_001', 'What is 15% of 200?', '20', '25', '30', '35', 'C', 'Convert 15% to a fraction of 100.', 1, 'RED', 'Mathematics', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_002', 'A ₹500 item is discounted by 10%. What is its sale price?', '₹440', '₹450', '₹460', '₹475', 'B', 'Find 10% of the marked price first.', 1, 'BLUE', 'Mathematics', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_003', 'If x + 7 = 19, what is x?', '10', '11', '12', '13', 'C', 'Undo the addition.', 1, 'GREEN', 'Mathematics', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_004', 'What is the average of 8, 12 and 16?', '10', '12', '14', '16', 'B', 'Add the three values, then divide by three.', 1, 'YELLOW', 'Mathematics', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_005', 'A train travels 60 km in 1.5 hours. What is its average speed?', '30 km/h', '40 km/h', '45 km/h', '50 km/h', 'B', 'Use distance divided by time.', 1, 'PINK', 'Mathematics', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_006', 'What is 3/4 of 48?', '32', '34', '36', '38', 'C', 'Divide 48 by 4, then multiply by 3.', 1, 'VIOLET', 'Mathematics', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_007', 'If 5 notebooks cost ₹150, what is the cost of one notebook?', '₹25', '₹30', '₹35', '₹40', 'B', 'Assume the notebooks have equal price.', 1, 'RED', 'Mathematics', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_008', 'What is the next number: 2, 5, 8, 11, ?', '12', '13', '14', '15', 'C', 'Look at the constant difference.', 1, 'BLUE', 'Mathematics', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_009', 'A ratio is 2:3. If the first part is 18, what is the second?', '24', '27', '30', '36', 'B', 'Scale both parts by the same factor.', 1, 'GREEN', 'Mathematics', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_010', 'What is 25²?', '525', '600', '625', '650', 'C', '25 × 25.', 1, 'YELLOW', 'Mathematics', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_011', 'A number increased by 20% becomes 120. What was the original number?', '90', '95', '100', '105', 'C', '120 represents 120% of the original.', 1, 'PINK', 'Mathematics', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_012', 'What is the perimeter of a rectangle 8 cm long and 5 cm wide?', '13 cm', '21 cm', '26 cm', '40 cm', 'C', 'Perimeter is twice length plus width.', 1, 'VIOLET', 'Mathematics', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_013', 'What is 0.6 × 50?', '20', '25', '30', '35', 'C', 'Six tenths of 50.', 1, 'RED', 'Mathematics', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_014', 'If 4 workers finish an identical task in 6 days, how many worker-days are used?', '10', '20', '24', '30', 'C', 'Multiply workers by days.', 1, 'BLUE', 'Mathematics', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_015', 'What is the smallest positive multiple of both 6 and 8?', '12', '18', '24', '48', 'C', 'Find the least common multiple.', 1, 'GREEN', 'Mathematics', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_016', 'A ₹800 bill has 5% tax added. What is the total?', '₹820', '₹830', '₹840', '₹850', 'C', 'Five percent of 800 is 40.', 1, 'YELLOW', 'Mathematics', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_017', 'What is 144 ÷ 12?', '10', '11', '12', '13', 'C', '12 multiplied by what gives 144?', 1, 'PINK', 'Mathematics', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_018', 'If 7 pens cost ₹84, what is the cost of 5 pens?', '₹50', '₹55', '₹60', '₹65', 'C', 'Find the unit price first.', 1, 'VIOLET', 'Mathematics', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_019', 'What is 2.5 + 3.75?', '5.75', '6.00', '6.25', '6.50', 'C', 'Align decimal places.', 1, 'RED', 'Mathematics', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_020', 'A class has 30 students and 18 are girls. What fraction are boys?', '2/5', '3/5', '1/2', '7/10', 'A', 'Count the boys before forming the fraction.', 1, 'BLUE', 'Mathematics', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_021', 'What is 18% of 50?', '7', '8', '9', '10', 'C', 'Ten percent plus eight percent.', 1, 'GREEN', 'Mathematics', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_022', 'If a = 4 and b = 3, what is a² + b²?', '19', '21', '25', '49', 'C', 'Square each value before adding.', 1, 'YELLOW', 'Mathematics', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_023', 'A clock gains 5 minutes every hour. How many minutes does it gain in 4 hours?', '10', '15', '20', '25', 'C', 'The gain is constant per hour.', 1, 'PINK', 'Mathematics', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_024', 'What is 5/8 expressed as a decimal?', '0.525', '0.625', '0.75', '0.8', 'B', 'Divide 5 by 8.', 1, 'VIOLET', 'Mathematics', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_025', 'A shop buys an item for ₹400 and sells it for ₹460. What is the profit?', '₹40', '₹50', '₹60', '₹70', 'C', 'Selling price minus cost price.', 1, 'RED', 'Mathematics', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_026', 'What is the median of 3, 7, 9, 12, 15?', '7', '8', '9', '12', 'C', 'The median is the middle ordered value.', 1, 'BLUE', 'Mathematics', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_027', 'A rectangle has area 48 cm² and width 6 cm. What is its length?', '6 cm', '7 cm', '8 cm', '9 cm', 'C', 'Area equals length times width.', 1, 'GREEN', 'Mathematics', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_028', 'What is 11 × 12?', '121', '132', '144', '156', 'B', 'Use 11 × 10 plus 11 × 2.', 1, 'YELLOW', 'Mathematics', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_029', 'A quantity falls from 80 to 60. What is the percentage decrease?', '20%', '25%', '30%', '35%', 'B', 'The decrease is measured relative to the original 80.', 1, 'PINK', 'Mathematics', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_030', 'If all roses are flowers and some flowers are red, which statement is definitely true?', 'All roses are red.', 'All red things are roses.', 'Every rose is a flower.', 'No rose is red.', 'C', 'Use only the first relationship.', 1, 'VIOLET', 'Logical Reasoning', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_031', 'Ravi is taller than Aman. Aman is taller than Dev. Who is shortest?', 'Ravi', 'Aman', 'Dev', 'Cannot be known', 'C', 'Order the three heights.', 1, 'RED', 'Logical Reasoning', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_032', 'If today is Monday, what day will it be after 10 days?', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'B', 'Reduce 10 by complete weeks.', 1, 'BLUE', 'Logical Reasoning', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_033', 'Find the odd one out: 16, 25, 36, 45.', '16', '25', '36', '45', 'D', 'Three are perfect squares.', 1, 'GREEN', 'Logical Reasoning', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_034', 'A is older than B, and C is younger than B. Who is oldest?', 'A', 'B', 'C', 'Cannot be known', 'A', 'Combine the two comparisons.', 1, 'YELLOW', 'Logical Reasoning', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_035', 'If CAT is coded as DBU by shifting each letter one step forward, DOG becomes:', 'EPH', 'EOG', 'CPH', 'EPG', 'A', 'Shift each letter by one.', 1, 'PINK', 'Logical Reasoning', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_036', 'Which number does not fit the pattern 2, 4, 8, 16, 31?', '4', '8', '16', '31', 'D', 'Check whether each term doubles.', 1, 'VIOLET', 'Logical Reasoning', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_037', 'A box contains only red and blue balls. If there are 7 red and 3 blue, how many balls are there?', '9', '10', '11', '12', 'B', 'Add the two groups.', 1, 'RED', 'Logical Reasoning', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_038', 'Neha faces north, turns right, then right again. Which direction is she facing?', 'North', 'East', 'South', 'West', 'C', 'Each right turn is 90 degrees.', 1, 'BLUE', 'Logical Reasoning', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_039', 'If 3 machines make 3 parts in 3 minutes at the same rate, how long does one machine take to make one part?', '1 minute', '3 minutes', '6 minutes', '9 minutes', 'B', 'Each machine makes one part in the three-minute interval.', 1, 'GREEN', 'Logical Reasoning', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_040', 'Which word comes first alphabetically?', 'Mango', 'Apple', 'Banana', 'Orange', 'B', 'Compare the first letters.', 1, 'YELLOW', 'Logical Reasoning', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_041', 'A meeting starts at 2:15 PM and lasts 45 minutes. When does it end?', '2:45 PM', '3:00 PM', '3:15 PM', '3:30 PM', 'B', 'Add 45 minutes.', 1, 'PINK', 'Logical Reasoning', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_042', 'If every square is a rectangle, which is guaranteed?', 'Every rectangle is a square.', 'Some squares are rectangles.', 'No square is a rectangle.', 'Every rectangle has four sides.', 'B', 'Use the stated subset relationship.', 1, 'VIOLET', 'Logical Reasoning', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_043', 'Four people stand in a line. P is before Q, and R is after Q. Which order could be valid?', 'Q-P-R-S', 'P-Q-R-S', 'R-Q-P-S', 'P-R-Q-S', 'B', 'Check both stated relations.', 1, 'RED', 'Logical Reasoning', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_044', 'A sequence alternates +2 and +3: 4, 6, 9, 11, 14, ?. What comes next?', '15', '16', '17', '18', 'B', 'Repeat the +2, +3 pattern.', 1, 'BLUE', 'Logical Reasoning', 'VERY_VERY_EASY', 20, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_045', 'Which planet is known for its prominent ring system?', 'Mars', 'Jupiter', 'Saturn', 'Venus', 'C', 'Think of the planet most famously shown with rings.', 1, 'GREEN', 'General Knowledge', 'VERY_VERY_EASY', 18, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_046', 'Which gas makes up most of Earth''s atmosphere?', 'Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen', 'B', 'It is roughly four-fifths of the atmosphere.', 1, 'YELLOW', 'General Knowledge', 'VERY_VERY_EASY', 18, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_047', 'What is the capital of Japan?', 'Kyoto', 'Osaka', 'Tokyo', 'Nagoya', 'C', 'It is Japan''s national capital.', 1, 'PINK', 'General Knowledge', 'VERY_VERY_EASY', 18, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_048', 'Which instrument measures temperature?', 'Barometer', 'Thermometer', 'Hygrometer', 'Altimeter', 'B', 'Its name is derived from thermo, meaning heat.', 1, 'VIOLET', 'General Knowledge', 'VERY_VERY_EASY', 18, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_049', 'How many sides does a hexagon have?', '5', '6', '7', '8', 'B', 'The prefix hexa- gives a clue.', 1, 'RED', 'General Knowledge', 'VERY_VERY_EASY', 18, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_050', 'Which ocean lies between Africa and Australia?', 'Atlantic', 'Pacific', 'Indian', 'Arctic', 'C', 'It is named after a country/region of the Indian subcontinent.', 1, 'BLUE', 'General Knowledge', 'VERY_VERY_EASY', 18, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_051', 'What is H2O commonly called?', 'Hydrogen peroxide', 'Water', 'Oxygen', 'Salt', 'B', 'It is the familiar compound made of hydrogen and oxygen.', 1, 'GREEN', 'General Knowledge', 'VERY_VERY_EASY', 18, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_052', 'Which metal is liquid at ordinary room temperature?', 'Iron', 'Copper', 'Mercury', 'Aluminium', 'C', 'It is traditionally used in some thermometers.', 1, 'YELLOW', 'General Knowledge', 'VERY_VERY_EASY', 18, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_053', 'Which is the largest continent by area?', 'Africa', 'Asia', 'Europe', 'South America', 'B', 'Think of the continent containing the largest share of Earth''s land area.', 1, 'PINK', 'General Knowledge', 'VERY_VERY_EASY', 18, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_054', 'What is the main organ used for pumping blood?', 'Lung', 'Liver', 'Heart', 'Kidney', 'C', 'It contracts rhythmically to circulate blood.', 1, 'VIOLET', 'General Knowledge', 'VERY_VERY_EASY', 18, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_055', 'A price of ₹800 is reduced by 15%. What is the new price?', '₹660', '₹680', '₹700', '₹720', 'B', 'Find 15% of ₹800 and subtract it.', 2, 'RED', 'Mathematics', 'VERY_EASY', 28, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_056', 'If 3x - 5 = 16, what is x?', '5', '6', '7', '8', 'C', 'Add 5, then divide by 3.', 2, 'BLUE', 'Mathematics', 'VERY_EASY', 28, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_057', 'The ratio of boys to girls is 3:5. If there are 24 boys, how many girls are there?', '32', '36', '40', '45', 'C', 'Scale the ratio so 3 becomes 24.', 2, 'GREEN', 'Mathematics', 'VERY_EASY', 28, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_058', 'What is the simple interest on ₹2,000 at 5% per year for 2 years?', '₹100', '₹150', '₹200', '₹250', 'C', 'Use principal × rate × time.', 2, 'YELLOW', 'Mathematics', 'VERY_EASY', 28, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_059', 'A car covers 180 km in 3 hours. At the same speed, how far in 5 hours?', '240 km', '270 km', '300 km', '330 km', 'C', 'First find the hourly speed.', 2, 'PINK', 'Mathematics', 'VERY_EASY', 28, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_060', 'What is the LCM of 9 and 12?', '18', '24', '36', '48', 'C', 'List common multiples or use prime factors.', 2, 'VIOLET', 'Mathematics', 'VERY_EASY', 28, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_061', 'A number is 30% less than 200. What is it?', '130', '140', '150', '160', 'B', 'Find 30% of 200 and subtract.', 2, 'RED', 'Mathematics', 'VERY_EASY', 28, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_062', 'The average of 5 numbers is 18. Their total is:', '72', '80', '90', '100', 'C', 'Average × number of values.', 2, 'BLUE', 'Mathematics', 'VERY_EASY', 28, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_063', 'A rectangle''s length is 12 cm and width 7 cm. Its area is:', '76', '84', '96', '98', 'B', 'Area is length × width.', 2, 'GREEN', 'Mathematics', 'VERY_EASY', 28, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_064', 'A ₹1,200 item is sold for ₹1,080. What is the discount percentage?', '8%', '10%', '12%', '15%', 'B', 'Compare the ₹120 reduction with the original price.', 2, 'YELLOW', 'Mathematics', 'VERY_EASY', 28, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_065', 'If 40% of a number is 72, what is the number?', '160', '170', '180', '190', 'C', '72 represents four tenths of the number.', 2, 'PINK', 'Mathematics', 'VERY_EASY', 28, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_066', 'What is 2/3 of 90?', '45', '50', '60', '75', 'C', 'Divide by 3, then multiply by 2.', 2, 'VIOLET', 'Mathematics', 'VERY_EASY', 28, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_067', 'A pipe fills 1/4 of a tank in 10 minutes at a constant rate. How long for the whole tank?', '20 min', '30 min', '40 min', '50 min', 'C', 'Four equal quarters are needed.', 2, 'RED', 'Mathematics', 'VERY_EASY', 28, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_068', 'A shopkeeper gains 25% on an item costing ₹600. Selling price?', '₹700', '₹725', '₹750', '₹800', 'C', 'Add one quarter of the cost.', 2, 'BLUE', 'Mathematics', 'VERY_EASY', 28, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_069', 'What is the next term: 3, 7, 15, 31, ?', '47', '55', '63', '65', 'C', 'Each term is double the previous term plus one.', 2, 'GREEN', 'Mathematics', 'VERY_EASY', 28, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_070', 'A fraction is 3/5. If numerator and denominator are both multiplied by 4, what is the new fraction?', '6/10', '9/15', '12/20', 'All are equivalent', 'D', 'Multiplying both parts preserves the value.', 2, 'YELLOW', 'Mathematics', 'VERY_EASY', 28, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_071', 'If 8 workers complete a job in 15 days, the total work is how many worker-days?', '100', '120', '125', '150', 'D', 'Multiply workers by days.', 2, 'PINK', 'Mathematics', 'VERY_EASY', 28, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_072', 'What is the perimeter of a square with area 81 cm²?', '18 cm', '27 cm', '36 cm', '40 cm', 'C', 'Find the side from the area first.', 2, 'VIOLET', 'Mathematics', 'VERY_EASY', 28, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_073', 'A number leaves remainder 2 when divided by 5. Which could be that number?', '17', '18', '20', '23', 'A', 'Check which value is two above a multiple of five.', 2, 'RED', 'Mathematics', 'VERY_EASY', 28, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_074', 'A train 120 m long passes a pole in 6 seconds. Its speed is:', '15 m/s', '20 m/s', '25 m/s', '30 m/s', 'B', 'Speed equals distance divided by time.', 2, 'BLUE', 'Mathematics', 'VERY_EASY', 28, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_075', 'Five people A, B, C, D, E stand in a line. A is before B, C is after B, and D is before A. Which must be true?', 'E is first', 'D is before C', 'C is before A', 'B is first', 'B', 'Chain the known order.', 2, 'GREEN', 'Logical Reasoning', 'VERY_EASY', 30, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_076', 'If BOOK is coded as CPPL, how is MATH coded using the same rule?', 'NBUI', 'NBSI', 'MBUI', 'NBTH', 'A', 'Shift every letter one step forward.', 2, 'YELLOW', 'Logical Reasoning', 'VERY_EASY', 30, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_077', 'A clock shows 3:00. What is the angle between the hands?', '60°', '90°', '120°', '180°', 'B', 'At exactly three, the hands are perpendicular.', 2, 'PINK', 'Logical Reasoning', 'VERY_EASY', 30, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_078', 'Find the missing number: 4, 9, 16, 25, ?', '30', '32', '36', '49', 'C', 'These are consecutive square numbers.', 2, 'VIOLET', 'Logical Reasoning', 'VERY_EASY', 30, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_079', 'If yesterday was Friday, what day is tomorrow?', 'Saturday', 'Sunday', 'Monday', 'Tuesday', 'B', 'Move two days forward from Friday.', 2, 'RED', 'Logical Reasoning', 'VERY_EASY', 30, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_080', 'A person walks 4 km north, then 4 km east. What is the shortest straight-line distance back to the start?', '4 km', '4√2 km', '8 km', '16 km', 'B', 'The path forms a right triangle.', 2, 'BLUE', 'Logical Reasoning', 'VERY_EASY', 30, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_081', 'Three switches correspond to three bulbs in another room. You may enter the room once. What key idea helps identify the switches?', 'Use different bulb positions', 'Use heat as well as light', 'Guess randomly', 'Turn all switches on', 'B', 'One bulb can be identified by being warm.', 2, 'GREEN', 'Logical Reasoning', 'VERY_EASY', 30, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_082', 'Which is the odd one out: 8, 27, 64, 100?', '8', '27', '64', '100', 'D', 'Three are perfect cubes.', 2, 'YELLOW', 'Logical Reasoning', 'VERY_EASY', 30, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_083', 'A is the brother of B. B is the sister of C. How is A related to C?', 'Brother', 'Sister', 'Father', 'Cannot be determined', 'A', 'A is male and shares the sibling link through B.', 2, 'PINK', 'Logical Reasoning', 'VERY_EASY', 30, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_084', 'In a code, 2→6, 3→12, 4→20. What does 5 map to?', '25', '30', '35', '40', 'B', 'Look for n multiplied by the next integer.', 2, 'VIOLET', 'Logical Reasoning', 'VERY_EASY', 30, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_085', 'A queue has P ahead of Q, and Q ahead of R. Who is behind P?', 'Only Q', 'Only R', 'Q and R', 'Cannot know', 'C', 'Both Q and R follow P.', 2, 'RED', 'Logical Reasoning', 'VERY_EASY', 30, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_086', 'Which arrangement is possible if X must be before Y and Z must be after Y?', 'Y-X-Z', 'X-Y-Z', 'Z-X-Y', 'Y-Z-X', 'B', 'Both conditions must hold.', 2, 'BLUE', 'Logical Reasoning', 'VERY_EASY', 30, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_087', 'A number pattern increases by 5, then 10, then 15: 7, 12, 22, 37, ?. Next:', '47', '52', '57', '62', 'C', 'The increments increase by five.', 2, 'GREEN', 'Logical Reasoning', 'VERY_EASY', 30, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_088', 'If SOUTH is written as HTUOS, what is the rule?', 'Letters shifted', 'Letters reversed', 'Letters sorted', 'Vowels removed', 'B', 'Compare the order of letters.', 2, 'YELLOW', 'Logical Reasoning', 'VERY_EASY', 30, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_089', 'Two statements: Some artists are teachers. All teachers read books. What follows?', 'All artists read books', 'Some artists read books', 'No artists read books', 'All readers are artists', 'B', 'The artists who are teachers inherit the teacher property.', 2, 'PINK', 'Logical Reasoning', 'VERY_EASY', 30, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_090', 'A worker earns ₹900 for 6 days. At the same daily rate, how much for 10 days?', '₹1,200', '₹1,350', '₹1,500', '₹1,800', 'C', 'Find the daily earning.', 2, 'VIOLET', 'Aptitude', 'VERY_EASY', 30, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_091', 'A tank has 60 L and 15 L are used. What percentage remains?', '60%', '65%', '70%', '75%', 'D', '45 L remain; compare with the original 60 L.', 2, 'RED', 'Aptitude', 'VERY_EASY', 30, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_092', 'A class has 40 students. 30% are absent. How many are present?', '26', '28', '30', '32', 'B', 'Find the absent count first.', 2, 'BLUE', 'Aptitude', 'VERY_EASY', 30, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_093', 'A recipe uses 3 cups of flour for 12 servings. How much for 20 servings?', '4 cups', '5 cups', '6 cups', '7 cups', 'B', 'Scale servings by the same factor.', 2, 'GREEN', 'Aptitude', 'VERY_EASY', 30, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_094', 'A bus leaves at 8:20 and arrives at 10:05. Travel time?', '1 h 25 min', '1 h 35 min', '1 h 45 min', '2 h 05 min', 'C', 'Count from 8:20 to 10:05.', 2, 'YELLOW', 'Aptitude', 'VERY_EASY', 30, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_095', 'If 5 identical items cost ₹275, what do 8 cost?', '₹400', '₹420', '₹440', '₹460', 'C', 'Find the price per item.', 2, 'PINK', 'Aptitude', 'VERY_EASY', 30, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_096', 'A student scores 72 out of 90. What percentage is that?', '70%', '75%', '80%', '85%', 'C', 'Convert the fraction 72/90 to a percentage.', 2, 'VIOLET', 'Aptitude', 'VERY_EASY', 30, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_097', 'A project is 3/8 complete. What fraction remains?', '3/8', '5/8', '1/2', '7/8', 'B', 'Subtract the completed fraction from one.', 2, 'RED', 'Aptitude', 'VERY_EASY', 30, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_098', 'A ₹2,000 salary rises by 8%. New salary?', '₹2,080', '₹2,120', '₹2,160', '₹2,180', 'C', 'Find 8% of ₹2,000.', 2, 'BLUE', 'Aptitude', 'VERY_EASY', 30, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_099', 'A machine produces 18 units in 6 minutes. At the same rate, how many in 10 minutes?', '24', '27', '30', '36', 'C', 'Find units per minute.', 2, 'GREEN', 'Aptitude', 'VERY_EASY', 30, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_100', 'Which layer of Earth is liquid and largely composed of iron and nickel?', 'Crust', 'Mantle', 'Outer core', 'Inner core', 'C', 'It surrounds the solid inner core.', 2, 'YELLOW', 'General Knowledge', 'VERY_EASY', 25, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_101', 'Which vitamin is commonly produced in skin in response to sunlight?', 'Vitamin A', 'Vitamin B12', 'Vitamin C', 'Vitamin D', 'D', 'Sunlight is strongly associated with it.', 2, 'PINK', 'General Knowledge', 'VERY_EASY', 25, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_102', 'Which Indian city is widely known as the Silicon Valley of India?', 'Pune', 'Bengaluru', 'Jaipur', 'Lucknow', 'B', 'It is a major technology hub.', 2, 'VIOLET', 'General Knowledge', 'VERY_EASY', 25, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_103', 'Which blood group is often called the universal red-cell donor?', 'AB+', 'AB−', 'O−', 'O+', 'C', 'Think of the absence of A, B and Rh antigens.', 2, 'RED', 'General Knowledge', 'VERY_EASY', 25, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_104', 'Which device converts electrical energy into mechanical motion?', 'Motor', 'Generator', 'Transformer', 'Resistor', 'A', 'It produces motion from electrical input.', 2, 'BLUE', 'General Knowledge', 'VERY_EASY', 25, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_105', 'What is the SI unit of electric current?', 'Volt', 'Watt', 'Ampere', 'Ohm', 'C', 'It is named after André-Marie Ampère.', 2, 'GREEN', 'General Knowledge', 'VERY_EASY', 25, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_106', 'Which is a renewable energy source?', 'Coal', 'Natural gas', 'Solar energy', 'Petroleum', 'C', 'It is replenished naturally.', 2, 'YELLOW', 'General Knowledge', 'VERY_EASY', 25, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_107', 'Which planet is closest to the Sun?', 'Venus', 'Earth', 'Mercury', 'Mars', 'C', 'It has the shortest orbital period among the planets.', 2, 'PINK', 'General Knowledge', 'VERY_EASY', 25, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_108', 'What does CPU stand for?', 'Central Processing Unit', 'Computer Primary Unit', 'Core Processing Utility', 'Central Program User', 'A', 'It is the main processing unit in a computer.', 2, 'VIOLET', 'General Knowledge', 'VERY_EASY', 25, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_109', 'Which process changes a liquid into a gas at the surface?', 'Condensation', 'Evaporation', 'Freezing', 'Deposition', 'B', 'It occurs from a liquid surface.', 2, 'RED', 'General Knowledge', 'VERY_EASY', 25, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_110', 'A number is increased by 25% and becomes 250. What was the original number?', '180', '200', '210', '225', 'B', '250 represents 125% of the original.', 3, 'BLUE', 'Mathematics', 'EASY', 38, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_111', 'A ₹1,500 item gets successive discounts of 10% and 20%. Final price?', '₹1,050', '₹1,080', '₹1,100', '₹1,120', 'B', 'Apply each discount to the price after the previous discount.', 3, 'GREEN', 'Mathematics', 'EASY', 38, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_112', 'If 2x + 7 = 31, x equals:', '10', '11', '12', '13', 'C', 'Subtract 7, then divide by 2.', 3, 'YELLOW', 'Mathematics', 'EASY', 38, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_113', 'A boat travels 36 km downstream in 3 hours. Average speed?', '9 km/h', '12 km/h', '15 km/h', '18 km/h', 'B', 'Distance divided by time.', 3, 'PINK', 'Mathematics', 'EASY', 38, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_114', 'The HCF of 36 and 48 is:', '6', '8', '12', '16', 'C', 'Use common factors or prime factorization.', 3, 'VIOLET', 'Mathematics', 'EASY', 38, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_115', 'A sum is divided in the ratio 4:7. If the smaller share is ₹280, total sum?', '₹700', '₹770', '₹840', '₹980', 'C', 'Find one ratio unit first.', 3, 'RED', 'Mathematics', 'EASY', 38, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_116', 'A rectangle has perimeter 50 cm and length 15 cm. Width?', '8 cm', '10 cm', '12 cm', '15 cm', 'B', 'Perimeter gives 2(length + width).', 3, 'BLUE', 'Mathematics', 'EASY', 38, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_117', 'A number is 40% of 350. What is it?', '120', '130', '140', '150', 'C', 'Multiply 350 by 0.4.', 3, 'GREEN', 'Mathematics', 'EASY', 38, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_118', 'An investment of ₹5,000 earns 6% simple interest annually. Interest after 3 years?', '₹600', '₹750', '₹900', '₹1,000', 'C', 'Use PRT/100.', 3, 'YELLOW', 'Mathematics', 'EASY', 38, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_119', 'If 12 men finish a job in 10 days, how many days for 15 men at the same rate?', '6', '8', '10', '12', 'B', 'Men × days remains constant.', 3, 'PINK', 'Mathematics', 'EASY', 38, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_120', 'What is the next term: 5, 11, 23, 47, ?', '71', '83', '95', '97', 'C', 'Double each term and add one.', 3, 'VIOLET', 'Mathematics', 'EASY', 38, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_121', 'A product is sold for ₹1,380 at a 15% profit. Cost price?', '₹1,150', '₹1,180', '₹1,200', '₹1,250', 'C', 'Selling price is 115% of cost.', 3, 'RED', 'Mathematics', 'EASY', 38, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_122', 'A square''s diagonal is 10√2 cm. Its side is:', '5 cm', '10 cm', '20 cm', '10√2 cm', 'B', 'Diagonal of a square is side × √2.', 3, 'BLUE', 'Mathematics', 'EASY', 38, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_123', 'If 3/7 of a number is 45, the number is:', '90', '95', '105', '120', 'C', 'Divide 45 by 3/7.', 3, 'GREEN', 'Mathematics', 'EASY', 38, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_124', 'A train travels half its journey at 60 km/h and half at 40 km/h. Average speed for the whole journey?', '45 km/h', '48 km/h', '50 km/h', '52 km/h', 'B', 'For equal distances, use total distance divided by total time.', 3, 'YELLOW', 'Mathematics', 'EASY', 38, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_125', 'The mean of 6 numbers is 14. If one number 9 is removed, mean of remaining five?', '14', '15', '16', '17', 'B', 'Total is 84; remove 9, then divide by five.', 3, 'PINK', 'Mathematics', 'EASY', 38, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_126', 'A quantity falls by 20% and then rises by 20%. Net change?', 'No change', '2% decrease', '4% decrease', '4% increase', 'C', 'Apply the second percentage to the reduced value.', 3, 'VIOLET', 'Mathematics', 'EASY', 38, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_127', 'What is the remainder when 137 is divided by 9?', '2', '3', '4', '5', 'C', 'Use the digit-sum test or division.', 3, 'RED', 'Mathematics', 'EASY', 38, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_128', 'A circle has radius 7 cm. Using π = 22/7, its circumference is:', '22 cm', '44 cm', '49 cm', '154 cm', 'B', 'Circumference is 2πr.', 3, 'BLUE', 'Mathematics', 'EASY', 38, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_129', 'A ₹2,400 bill is split equally among 8 people, then each person pays ₹50 extra for a service. Total paid?', '₹2,450', '₹2,800', '₹3,000', '₹3,200', 'C', 'Add ₹50 to each person''s share.', 3, 'GREEN', 'Mathematics', 'EASY', 38, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_130', 'Six books P,Q,R,S,T,U are arranged. P is before Q, Q before R, and S is after R. Which must be true?', 'S is before P', 'P is before S', 'U is before P', 'T is after S', 'B', 'Chain P → Q → R → S.', 3, 'YELLOW', 'Logical Reasoning', 'EASY', 40, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_131', 'In a code, 246 means ''red small box'' and 684 means ''small blue car''. Which digit represents small?', '2', '4', '6', '8', 'C', 'Find the common word and common digit.', 3, 'PINK', 'Logical Reasoning', 'EASY', 40, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_132', 'A person faces east, turns left, walks, then turns left again. Final direction?', 'East', 'West', 'North', 'South', 'B', 'Two left turns reverse the direction.', 3, 'VIOLET', 'Logical Reasoning', 'EASY', 40, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_133', 'Find the missing term: 2, 6, 12, 20, 30, ?', '36', '40', '42', '44', 'C', 'Look at products of consecutive integers.', 3, 'RED', 'Logical Reasoning', 'EASY', 40, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_134', 'Four friends A,B,C,D have different scores. A > B, C > A, and D < B. Who has the highest score?', 'A', 'B', 'C', 'D', 'C', 'Build the complete order.', 3, 'BLUE', 'Logical Reasoning', 'EASY', 40, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_135', 'If MONDAY is coded as 1234567, what code could represent DAY using the same letter positions?', '567', '567?', '456', '367', 'A', 'Use the positions of D, A and Y in MONDAY.', 3, 'GREEN', 'Logical Reasoning', 'EASY', 40, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_136', 'A statement says: All engineers are graduates. Some graduates are musicians. What is definitely possible?', 'Some engineers may be musicians.', 'No engineer can be a musician.', 'All musicians are engineers.', 'All graduates are engineers.', 'A', 'The two groups can overlap without contradiction.', 3, 'YELLOW', 'Logical Reasoning', 'EASY', 40, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_137', 'A sequence follows ×2, −1 repeatedly: 6, 12, 11, 22, 21, ?', '40', '41', '42', '43', 'B', 'Continue the same two-step cycle.', 3, 'PINK', 'Logical Reasoning', 'EASY', 40, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_138', 'Five seats are numbered 1–5. K sits in seat 3. L sits immediately to the right of K. Which seat is L in?', '2', '3', '4', '5', 'C', 'Immediately right means one higher number.', 3, 'VIOLET', 'Logical Reasoning', 'EASY', 40, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_139', 'If the letters of ''REACT'' are rearranged alphabetically, which is first?', 'A', 'C', 'E', 'R', 'A', 'Sort the letters alphabetically.', 3, 'RED', 'Logical Reasoning', 'EASY', 40, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_140', 'A family has two parents and three children. Each child has one sibling. How many people are in the family?', '4', '5', '6', '7', 'B', 'The three children belong to the same sibling group.', 3, 'BLUE', 'Logical Reasoning', 'EASY', 40, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_141', 'Which conclusion follows: Some cats are black; all black things are visible. Therefore:', 'All cats are visible.', 'Some cats are visible.', 'No cats are visible.', 'All visible things are cats.', 'B', 'Apply the second statement to the black cats.', 3, 'GREEN', 'Logical Reasoning', 'EASY', 40, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_142', 'A code adds the position of each letter: A=1, B=2, etc. What is the value of CAT?', '22', '24', '25', '26', 'B', 'Add the three letter positions.', 3, 'YELLOW', 'Logical Reasoning', 'EASY', 40, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_143', 'Three tasks A,B,C must be done one at a time. A must occur before B, and B before C. Which order is forced?', 'A-C-B', 'B-A-C', 'A-B-C', 'C-B-A', 'C', 'Both precedence conditions point in one direction.', 3, 'PINK', 'Logical Reasoning', 'EASY', 40, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_144', 'A number is described as greater than 20, even, and divisible by 3. Which option fits?', '21', '22', '24', '27', 'C', 'Check all three properties.', 3, 'VIOLET', 'Logical Reasoning', 'EASY', 40, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_145', 'A shop''s sales rise from ₹40,000 to ₹46,000. Percentage increase?', '10%', '12%', '15%', '20%', 'C', 'The increase is ₹6,000 on ₹40,000.', 3, 'RED', 'Aptitude', 'EASY', 42, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_146', 'A team completes 60% of a task in 18 days at a constant rate. Total time?', '24 days', '27 days', '30 days', '36 days', 'C', '18 days corresponds to 60%.', 3, 'BLUE', 'Aptitude', 'EASY', 42, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_147', 'A car uses 8 L of fuel for 120 km. At the same efficiency, fuel for 300 km?', '16 L', '18 L', '20 L', '24 L', 'C', 'Find kilometres per litre.', 3, 'GREEN', 'Aptitude', 'EASY', 42, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_148', 'A class average is 68 for 20 students. If a new student scoring 88 joins, new average?', '68.5', '68.95', '69', '70', 'B', 'Update the total first, then divide by 21.', 3, 'YELLOW', 'Aptitude', 'EASY', 42, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_149', 'A worker finishes 3/5 of a job in 12 hours. At the same rate, full job takes:', '18 h', '20 h', '24 h', '30 h', 'B', 'Scale 12 hours by 5/3.', 3, 'PINK', 'Aptitude', 'EASY', 42, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_150', 'A product marked ₹2,000 is sold after a 10% discount, then 5% tax is added. Final price?', '₹1,800', '₹1,890', '₹1,900', '₹1,950', 'B', 'Discount first, tax second.', 3, 'VIOLET', 'Aptitude', 'EASY', 42, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_151', 'A train''s speed increases from 50 km/h to 60 km/h. For a fixed distance, travel time changes by what percentage?', '10% decrease', '16.67% decrease', '20% decrease', '20% increase', 'B', 'Time is inversely proportional to speed for fixed distance.', 3, 'RED', 'Aptitude', 'EASY', 42, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_152', 'A mixture contains milk and water in ratio 5:2. If total is 28 L, how much water?', '6 L', '8 L', '10 L', '12 L', 'B', 'There are seven equal parts.', 3, 'BLUE', 'Aptitude', 'EASY', 42, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_153', 'A student answers 36 of 45 questions correctly. Accuracy?', '75%', '80%', '85%', '90%', 'B', 'Correct answers divided by total.', 3, 'GREEN', 'Aptitude', 'EASY', 42, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_154', 'A project budget of ₹80,000 has 25% reserved for testing. How much remains for other work?', '₹50,000', '₹55,000', '₹60,000', '₹65,000', 'C', 'Subtract one quarter of the budget.', 3, 'YELLOW', 'Aptitude', 'EASY', 42, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_155', 'What comes next: 1, 4, 9, 16, 25, ?', '30', '32', '36', '49', 'C', 'These are squares of consecutive integers.', 3, 'PINK', 'Pattern Recognition', 'EASY', 40, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_156', 'What comes next: 2, 6, 18, 54, ?', '108', '144', '162', '216', 'C', 'Multiply by the same factor each time.', 3, 'VIOLET', 'Pattern Recognition', 'EASY', 40, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_157', 'What comes next: 81, 27, 9, 3, ?', '0', '1', '2', '3', 'B', 'Each term is divided by three.', 3, 'RED', 'Pattern Recognition', 'EASY', 40, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_158', 'Find the missing number: 3, 8, 15, 24, 35, ?', '46', '48', '50', '52', 'B', 'Differences increase by 2 each time.', 3, 'BLUE', 'Pattern Recognition', 'EASY', 40, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_159', 'What comes next: 10, 13, 19, 28, 40, ?', '52', '55', '57', '60', 'B', 'Differences are 3,6,9,12.', 3, 'GREEN', 'Pattern Recognition', 'EASY', 40, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_160', 'Which value breaks the pattern: 4, 8, 16, 32, 60?', '8', '16', '32', '60', 'D', 'The pattern doubles each term.', 3, 'YELLOW', 'Pattern Recognition', 'EASY', 40, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_161', 'What comes next: 100, 90, 72, 48, ?', '30', '24', '20', '18', 'C', 'Subtract 10, 18, 24; look at the changing differences?', 3, 'PINK', 'Pattern Recognition', 'EASY', 40, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_162', 'What comes next: 5, 10, 20, 40, 80, ?', '120', '140', '160', '180', 'C', 'Each term doubles.', 3, 'VIOLET', 'Pattern Recognition', 'EASY', 40, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_163', 'A sequence is 7, 14, 28, 56. What is the next term?', '84', '98', '112', '120', 'C', 'Continue doubling.', 3, 'RED', 'Pattern Recognition', 'EASY', 40, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_164', 'What is the missing number: 2, 5, 10, 17, 26, ?', '35', '36', '37', '38', 'C', 'Add consecutive odd numbers.', 3, 'BLUE', 'Pattern Recognition', 'EASY', 40, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_165', 'Which gas is released by plants during photosynthesis?', 'Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen', 'A', 'Think about the gas humans need for respiration.', 3, 'GREEN', 'General Knowledge', 'EASY', 45, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_166', 'Which is the smallest prime number?', '0', '1', '2', '3', 'C', 'A prime has exactly two positive divisors.', 3, 'YELLOW', 'General Knowledge', 'EASY', 45, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_167', 'Which Indian state has Jaipur as its capital?', 'Gujarat', 'Rajasthan', 'Madhya Pradesh', 'Haryana', 'B', 'Jaipur is a major city in north-western India.', 3, 'PINK', 'General Knowledge', 'EASY', 45, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_168', 'What does RAM primarily provide to a running computer?', 'Permanent storage', 'Temporary working memory', 'Internet access', 'Power supply', 'B', 'It holds data and instructions currently in use.', 3, 'VIOLET', 'General Knowledge', 'EASY', 45, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_169', 'Which fraction is greatest?', '3/8', '1/2', '5/12', '7/16', 'B', 'Convert them to comparable values.', 3, 'RED', 'Mathematics', 'EASY', 45, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_170', 'If a 12% tax on ₹2,500 is added, the total is:', '₹2,700', '₹2,750', '₹2,800', '₹2,850', 'C', 'Find 12% of ₹2,500.', 3, 'BLUE', 'Mathematics', 'EASY', 45, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_171', 'A 4-digit number has thousands digit 3, hundreds digit 5, tens digit 2 and units digit 7. What is the number?', '3527', '3572', '3257', '3725', 'A', 'Read the place values in order.', 3, 'GREEN', 'Logical Reasoning', 'EASY', 45, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_172', 'A person buys 3 items at ₹240 each and receives a total discount of ₹90. Amount paid?', '₹570', '₹620', '₹630', '₹650', 'C', 'Find the original total, then subtract the discount.', 3, 'YELLOW', 'Aptitude', 'EASY', 45, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_173', 'If 5% of a number is 12, what is 25% of the same number?', '48', '60', '72', '84', 'B', 'Twenty-five percent is five times five percent.', 3, 'PINK', 'Mathematics', 'EASY', 45, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_174', 'Which option is divisible by both 4 and 6?', '18', '20', '24', '30', 'C', 'It must be divisible by the LCM of 4 and 6.', 3, 'VIOLET', 'Mathematics', 'EASY', 45, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_175', 'A meeting has 8 people. Everyone shakes hands with every other person exactly once. How many handshakes?', '28', '32', '36', '56', 'A', 'Count each pair only once.', 3, 'RED', 'Puzzles', 'EASY', 45, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_176', 'A bag has 5 red, 3 blue and 2 green balls. Probability of drawing a blue ball?', '1/5', '3/10', '1/3', '2/5', 'B', 'Blue outcomes over total outcomes.', 3, 'BLUE', 'Aptitude', 'EASY', 45, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_177', 'A number is both a multiple of 8 and 12. Which is the smallest positive possibility?', '16', '20', '24', '48', 'C', 'Find the LCM.', 3, 'GREEN', 'Mathematics', 'EASY', 45, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_178', 'If TODAY is coded by moving each letter two positions forward, T becomes:', 'U', 'V', 'W', 'X', 'B', 'Move two alphabet positions forward.', 3, 'YELLOW', 'Logical Reasoning', 'EASY', 45, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_179', 'Which statement must be true for a number divisible by 10?', 'It is odd.', 'Its last digit is 0.', 'It is divisible by 3.', 'Its first digit is 1.', 'B', 'Use the divisibility rule for 10.', 3, 'PINK', 'Logical Reasoning', 'EASY', 45, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED'),
('MME180_180', 'A 2-hour lecture starts at 9:40 AM and has a 15-minute break after 50 minutes. If the break is included in the total schedule, when does it finish?', '11:30 AM', '11:45 AM', '11:55 AM', '12:00 PM', 'B', 'Add 50 minutes, the 15-minute break, then the remaining 70 minutes.', 3, 'VIOLET', 'Aptitude', 'EASY', 45, 'NEEDS_HUMAN_REVIEW', false, 'original_generated_seed', '50_MILLIONAIRE_180_EASY_SEED')
ON CONFLICT (external_id) DO NOTHING;

-- Safety checks: exactly these new IDs should exist after import.
DO $$
DECLARE
  total_new integer;
  bad_rows integer;
BEGIN
  SELECT count(*) INTO total_new
  FROM public.questions
  WHERE external_id LIKE 'MME180_%';

  SELECT count(*) INTO bad_rows
  FROM public.questions
  WHERE external_id LIKE 'MME180_%'
    AND (
      level NOT BETWEEN 1 AND 3
      OR difficulty NOT IN ('VERY_VERY_EASY','VERY_EASY','EASY')
      OR active <> false
      OR verification_status <> 'NEEDS_HUMAN_REVIEW'
    );

  IF total_new <> 180 THEN
    RAISE EXCEPTION 'Expected 180 MME180 rows, found %', total_new;
  END IF;

  IF bad_rows <> 0 THEN
    RAISE EXCEPTION 'Found % malformed MME180 rows', bad_rows;
  END IF;
END $$;

COMMIT;
